use std::{
    env,
    ffi::OsStr,
    fs,
    io::Write,
    path::{Path, PathBuf},
};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let icons_dir = manifest_dir.join("../../assets/icons");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", icons_dir.display());

    if !icons_dir.is_dir() {
        panic!(
            "expected icons directory at {}, but it does not exist",
            icons_dir.display()
        );
    }

    let mut icon_files: Vec<PathBuf> = Vec::new();
    if let Ok(read_dir) = fs::read_dir(&icons_dir) {
        for entry in read_dir.flatten() {
            let path = entry.path();
            let is_supported_icon = matches!(
                path.extension().and_then(OsStr::to_str),
                Some("svg" | "png")
            );
            if is_supported_icon && path.is_file() {
                icon_files.push(path);
            }
        }
    }

    icon_files.sort_by(|a, b| a.file_name().cmp(&b.file_name()));

    if icon_files.is_empty() {
        panic!(
            "no supported icons found in {}, cannot generate TermuaIcon enum",
            icons_dir.display()
        );
    }

    for path in &icon_files {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("termua_icons.rs");

    let mut out = String::new();
    out.push_str("// @generated by crates/gpui_common/build.rs - DO NOT EDIT.\n");
    out.push_str("asset_icons! {\n");
    out.push_str("    pub enum TermuaIcon {\n");

    for path in &icon_files {
        let file_name = path
            .file_name()
            .and_then(|s| s.to_str())
            .expect("icon file name should be valid utf-8");
        let stem = Path::new(file_name)
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("icon stem should be valid utf-8");

        let variant = to_rust_ident(stem);
        let asset_path = format!("icons/{file_name}");

        out.push_str(&format!("        {variant} => \"{asset_path}\",\n"));
    }

    out.push_str("    }\n");
    out.push_str("}\n");

    let mut f = fs::File::create(&dest).expect("create termua_icons.rs");
    f.write_all(out.as_bytes()).expect("write termua_icons.rs");
}

fn to_rust_ident(stem: &str) -> String {
    let mut out = String::new();
    for part in stem
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|p| !p.is_empty())
    {
        if part.chars().all(|c| c.is_ascii_digit()) {
            out.push_str(part);
            continue;
        }

        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.push(first.to_ascii_uppercase());
            for c in chars {
                out.push(c.to_ascii_lowercase());
            }
        }
    }

    if out.is_empty() {
        "Icon".to_string()
    } else if out.chars().next().unwrap().is_ascii_digit() {
        format!("Icon{out}")
    } else {
        out
    }
}
